name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Jekyll site
        run: |
          docker run \
            --volume ${{ github.workspace }}:/srv/jekyll \
            --volume ${{ github.workspace }}/_site:/srv/jekyll/_site \
            --user 1001:121 \
            jekyll/jekyll \
            jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
